### ISSUE TITLE
Running in an AWS lambda ? 

### ISSUE THREAD

**Issue by Mylab6** [spotify/basic-pitch#10]
Hi, is it possible to run this in an AWS lambda, and could you provide instructions on how to do so ?

**Comment by drubinstein** [comment]
Hi. Not really a heavy user of AWS (Spotify primarily uses GCP), but I can't see why this wouldn't work within an AWS lambda. You'd most likely have to [create your own container](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) with basic-pitch installed + any audio reading libraries you may want e.g. pedalboard, ffmpeg etc. Then deploy that image and let it run.

The bigger question is how you want to pass data to the lambda. You could pass in raw audio data, but I assume that may be expensive if AWS Lambda charges by in/out bytes. You could also pass in a string pointing to a location in AWS S3, an FTP server etc. that you then use to download the file and process it in basic pitch.

**Comment by Mylab6** [comment]
Thanks for the response, if I continue with this, I'd probably upload the file to S3 first. 

If you have a GCP example, that would also be great

**Comment by drubinstein** [comment]
I dont have any examples, but I believe any of the tutorials with [GCP Cloud functions](https://cloud.google.com/functions/docs/tutorials) should suffice with a custom [cloud function image](https://cloud.google.com/functions/docs/building)
