### ISSUE TITLE
Windows 10, Python 3.8, ModuleNotFoundError: No module named 'basic_pitch.predict'

### ISSUE THREAD

**Issue by mdwhitis** [spotify/basic-pitch#11]
I installed basic-pitch ok but when I run it I get:

PS C:\Users\y\Desktop>  basic-pitch.exe .\Lifeblood '..\Downloads\That Petrol Emotion - Lifeblood -1986.mp3'
Traceback (most recent call last):
  File "C:\Users\y\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\y\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\y\AppData\Local\Programs\Python\Python38\Scripts\basic-pitch.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'basic_pitch.predict'

**Comment by lividhen** [comment]
We're there any incompatible packages during installation? (six and typing-extensions). I had to downgrade both these packages to get it to work.

**Comment by drubinstein** [comment]
Hi. I'm having trouble reproducing this on windows. Can you explain how you installed basic-pitch? In addition, can you try running with `python3 -m basic_pitch .\Lifeblood '..\Downloads\That Petrol Emotion - Lifeblood -1986.mp3'`?

Thanks!

**Comment by mdwhitis** [comment]
python.exe -m basic-pitch .\Lifeblood '..\Downloads\That Petrol Emotion - Lifeblood -1986.mp3'
C:\Users\y\AppData\Local\Programs\Python\Python38\python.exe: No module named basic-pitch

**Comment by drubinstein** [comment]
That implies you dont have basic pitch installed for that python. Maybe you have multiple versions on your machine or you have a virtualenv that you dont know about. Can you try running
```
python.exe -m pip install basic-pitch
```
and then rerunning?

**Comment by mdwhitis** [comment]
here's the output for 

python.exe -m pip install basic-pitch

Requirement already satisfied: basic_pitch in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (0.0.1)
Requirement already satisfied: tensorflow<2.7.0,>=2.4.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (2.6.5)
Requirement already satisfied: pretty-midi>=0.2.9 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (0.2.9)
Requirement already satisfied: resampy>=0.2.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (0.2.2)
Requirement already satisfied: typing-extensions in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (3.10.0.2)
Requirement already satisfied: numpy<1.20,>=1.19.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (1.19.5)
Requirement already satisfied: librosa>=0.8.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (0.9.1)
Requirement already satisfied: mir-eval>=0.6 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (0.7)
Requirement already satisfied: scipy>=1.4.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from basic_pitch) (1.8.1)
Requirement already satisfied: soundfile>=0.10.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (0.10.3.post1)
Requirement already satisfied: joblib>=0.14 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (1.1.0)
Requirement already satisfied: numba>=0.45.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (0.55.2)
Requirement already satisfied: decorator>=4.0.10 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (5.1.1)
Requirement already satisfied: pooch>=1.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (1.6.0)
Requirement already satisfied: audioread>=2.1.5 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (2.1.9)
Requirement already satisfied: packaging>=20.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (21.3)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from librosa>=0.8.0->basic_pitch) (1.1.1)
Requirement already satisfied: future in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from mir-eval>=0.6->basic_pitch) (0.18.2)
Requirement already satisfied: six in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from mir-eval>=0.6->basic_pitch) (1.15.0)
Requirement already satisfied: mido>=1.1.16 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from pretty-midi>=0.2.9->basic_pitch) (1.2.10)
Requirement already satisfied: tensorboard<2.7,>=2.6.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (2.6.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.1.2)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.6.3)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.1.0)
Requirement already satisfied: clang~=5.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (5.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.19.4)
Requirement already satisfied: tensorflow-estimator<2.7,>=2.6.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (2.6.0)
Requirement already satisfied: absl-py~=0.10 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.15.0)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.12.1)
Requirement already satisfied: keras<2.7,>=2.6.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (2.6.0)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.12)
Requirement already satisfied: wheel~=0.35 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.37.1)
Requirement already satisfied: google-pasta~=0.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.37.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.46.3)
Requirement already satisfied: gast==0.4.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.4.0)
Requirement already satisfied: h5py~=3.1.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.1.0)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.3.0)
Requirement already satisfied: setuptools in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from numba>=0.45.1->librosa>=0.8.0->basic_pitch) (56.0.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from numba>=0.45.1->librosa>=0.8.0->basic_pitch) (0.38.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from packaging>=20.0->librosa>=0.8.0->basic_pitch) (3.0.9)
Requirement already satisfied: appdirs>=1.3.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from pooch>=1.0->librosa>=0.8.0->basic_pitch) (1.4.4)
Requirement already satisfied: requests>=2.19.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from pooch>=1.0->librosa>=0.8.0->basic_pitch) (2.27.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn>=0.19.1->librosa>=0.8.0->basic_pitch) (3.1.0)
Requirement already satisfied: cffi>=1.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from soundfile>=0.10.2->librosa>=0.8.0->basic_pitch) (1.15.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (2.1.2)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.35.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.3.7)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.8.1)
Requirement already satisfied: pycparser in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.0->soundfile>=0.10.2->librosa>=0.8.0->basic_pitch) (2.21)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (4.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (4.11.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.19.0->pooch>=1.0->librosa>=0.8.0->basic_pitch) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.19.0->pooch>=1.0->librosa>=0.8.0->basic_pitch) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.19.0->pooch>=1.0->librosa>=0.8.0->basic_pitch) (2022.5.18.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.19.0->pooch>=1.0->librosa>=0.8.0->basic_pitch) (2.0.12)
Requirement already satisfied: zipp>=0.5 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.8.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\y\appdata\local\programs\python\python38\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow<2.7.0,>=2.4.1->basic_pitch) (3.2.0)

**Comment by drubinstein** [comment]
How about `python.exe -m basic_pitch .\Lifeblood '..\Downloads\That Petrol Emotion - Lifeblood -1986.mp3'`

Apologies for the back and forth. I dont have easy access to a windows machine so I'm kind of guessing here.

**Comment by drubinstein** [comment]
Ah correction to the above
```
python.exe -m basic_pitch.predict
```

**Comment by mdwhitis** [comment]
it says it can't find it... I've given up and am installing it in alpine linux running under the windows subsystem for linux.

thanks for your help
