### ISSUE TITLE
Transition from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by egndz** [spotify/basic-pitch#110]
Objective:

Change from the legacy setup.py configuration to the modern pyproject.toml standard. This change aligns with PEP 518 and PEP 621, offering better build system declaration and metadata management.

Benefits:
- Simplified build and packaging process
- Enhanced metadata handling
- Better dependency management
- Improved project maintainability

Action:

Replace existing setup.py with a comprehensive pyproject.toml file, ensuring compatibility and functionality are maintained.

Requesting assistance for:
- Drafting an initial pyproject.toml configuration
- Testing for seamless transition
- Updating documentation to reflect changes

**Comment by drubinstein** [comment]
Hi @egndz. I already did the conversion to pyproject.toml in #100 . Unfortunately, I'm blocked on furthering that PR because it won't work on GitHub's Intel Mac instances. I can extract the pyproject.toml changes and PR it separately later this week.

**Comment by egndz** [comment]
Sounds good, let's split the pyproject.toml changes. Thank you for the consideration

**Comment by drubinstein** [comment]
Merged as a part of #111 .
