### ISSUE TITLE
Piano roll, web demo, tweak nice to have

### ISSUE THREAD

**Issue by opencoca** [spotify/basic-pitch#115]
At the moment there's no visible time signature or bar lines in the visualization for the midi information. It would be wonderful if while people are exploring and adjusting the tempo, they could see how their notes fell on it.

**Comment by opencoca** [comment]
On further review I see that changing the tempo doesn't affect how the music is analyzed but instead only the tempo the resulting midi. IE at the moment changing the tempo changes the length of the resulting midi.

**Comment by drubinstein** [comment]
The typescript library that powers the demo is [open source on github](https://github.com/spotify/basic-pitch-ts) and available via [npm](https://www.npmjs.com/package/@spotify/basic-pitch).

The web demo is internal and not open sourced however. And yes, your further review is correct.

**Comment by opencoca** [comment]
If you choose to share the web demo I would be happy to tweak things. You could always publish it under AGPL so that code developed by you and the open source community stays available, and it prevents others from repackaging and selling your open-sourced software. I also understand if corporate doesn't want any AGLP, as a number of companies (I'm looking at you Google) don't allow AGPL.

**Comment by drubinstein** [comment]
Of course. We'll talk about it internally. I'm going to close this issue for now, but if we ever decide to open source the website, I'll add a message to this issue.
