### ISSUE TITLE
[Bug] AttributeError: module 'scipy.signal' has no attribute 'gaussian'

### ISSUE THREAD

**Issue by Davilarek** [spotify/basic-pitch#120]
**Describe the bug**
Fresh install of `basic-pitch` inside a venv throws error on any sound file provided.
Error message: `AttributeError: module 'scipy.signal' has no attribute 'gaussian'`

**To Reproduce**
1. Make a venv and get into it
2. Install `basic-pitch`
3. Execute `basic-pitch <output dir> <input file>`
4. Wait some seconds
5. See error

**Expected behavior**
For basic pitch to work

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.3.0

**Additional context**
Here's log:

[log.txt](https://github.com/spotify/basic-pitch/files/14899274/log.txt)

**Comment by TeeJayBaker** [comment]
Downgrading scipy from 1.13 to 1.12 will fix the issue temporarily
scipy.signal.gaussian has been replaced with scipy.signal.windows.gaussian

**Comment by drubinstein** [comment]
Fixed in the 0.3.1 release
