### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mslinn** [spotify/basic-pitch#125]
```
Just a little review I wrote.
I hope you read it note for note.
Don't worry,
Be happy.
```

https://www.mslinn.com/av_studio/760-ai-midi.html

You are welcome to leave a comment here, or contact me directly.

**Comment by bgenchel** [comment]
Perhaps this should be the actual issue brought up in this section - "I found that attempting a second conversion would fail unless I refreshed the web page first."
