### ISSUE TITLE
Output of one Piano cover is a MIDI with 62 instruments in MuseScore

### ISSUE THREAD

**Issue by kevinlinxc** [spotify/basic-pitch#14]
Hi, I input a cover of a piano song into the Python library, and opened the resulting MIDI file in MuseScore. This was the result:
![image](https://user-images.githubusercontent.com/44324811/172284948-090f6ce3-2d14-4f93-8286-cc0fd8017894.png)
Essentially, there were a few notes played by 62 different pianos, despite the original performance being played on 1.

Is this expected behaviour from basic-pitch? ~~Is it because I don't have the CUDA dependencies?~~ Installed CUDA and cuDNN. 

If it is expected behaviour, I'm looking for some angles to attack this problem from on the MuseScore side and the Basic-Pitch side. 
Any help would be appreciated.

**Comment by kevinlinxc** [comment]
Tried all of the following, unsuccessfully:

1. Merging with Tools->Implode in Musescore (Does nothing): https://musescore.org/en/node/332630
2. This Python script: https://github.com/m13253/midi-track-merge (Converted to 16 tracks, still not what I wanted, repeated uses leads to errors)
3. Miditocsv, edit first column, csvtomidi: https://www.fourmilab.ch/webtools/midicsv (Didn't change anything, strangely)
4. [My own script](https://gist.github.com/kevinlinxc/54da6493ddd1aaed959e1b3b72afc0e2) to turn Basic Pitch's csv into a MIDI. Sounds decent, but timing is obviously off and I'm not sure how to calculate the proper time in beats from the given time in seconds. https://streamable.com/vkmahx
5. [This library](https://github.com/vishnubob/python-midi/issues/184#issue-630465125) and [this code](https://stackoverflow.com/a/53981529) (does nothing)

**Comment by kevinlinxc** [comment]
I ended up getting to merge by modifying mido, the package behind pretty midi - still didn't look pretty, but it was on one track at least. 
```
import os
import mido

mid = mido.MidiFile(os.path.join("outputs", "bakamitai_basic_pitch.mid"))
merged_track = mido.merge_tracks(mid.tracks)
new_midi= mido.MidiFile()
new_midi.tracks=[merged_track]
new_midi.save("merged.mid")
```

mido/midifiles/tracks.py:
`def _to_abstime(messages):
    """Convert messages to absolute time."""
    now = 0
    for msg in messages:
        now += msg.time
        try:
            msg.channel = 1
        except:
            pass
        yield msg.copy(time=now)

The remaining problem is that MIDI -> sheet music has not come far enough yet.

**Comment by kevinlinxc** [comment]
Hi, I just tried using main (no master branch). I downloaded the zip, unzipped it, and then called my venv/Scripts/python setup.py install to install it. The output is still the same. The version number also still seems to be 0.0.1. Am I doing anything wrong?

**Comment by Misfire2** [comment]
Thanks for this information and update and everyone's work on basic pitch. I had come to ask about the same topic and found this thread.  Your web based version at spotify produced a very accurate sounding single track, while the command line version split the same audio sample out to about 30 tracks. I manually combined all those in to one within my daw, but the result didn't sound as accurate as the web based tool . I considered trying the repository, but in reading kevinglinxc's last message, I think I'll just look forward to the next version on PyPi if it will be coming soon.

**Comment by neo-anderson** [comment]
I tried installing directly from GitHub and I'm facing the same issue. Dragging and dropping the MIDI file into Ableton Live creates a lot of MIDI tracks. MIDI output of the webapp only creates one track.

**Comment by Misfire2** [comment]
This eve I took a look at the repository diffs and pulled down the latest versions of inference, note_creation, and predict. I directly replaced those files in my module folder and now I'm now generating the same single track midi files that the webtool was providing. yay

**Comment by neo-anderson** [comment]
@Misfire2 I followed your method, but I'm still getting multiple tracks in the output MIDI. I diffed the files and they're the same as the ones in the repo. Can you please share your command/function call?
I noticed something just now. If I run basic-pitch via the terminal with command `basic-pitch output_folder input.wav`, I get a MIDI file with a single track. However, if I call the `predict_and_save` function in a python script, I get a MIDI file back with multiple tracks. I compared the arguments and they are the same and mostly just the defaults. Any clue?

**Comment by Misfire2** [comment]
I'm working from a windows box and have only been using the command line option ...
/>basic-pitch output-folder input-file .  From the start, even command line was giving me multiple tracks.
Once I replaced the 3 files, command line produced just the single track.
My setup might be slightly different than your because I originally installed the package from https://pypi.org/project/basic-pitch/    I didn't use the entire repository version, I only replace those 3 files while leaving the rest of the  pypi package in place.  I'm just a C++ guy and haven't delved deeper in to the code since I was getting the basic function I needed from command line.

**Comment by rabitt** [comment]
Just a quick update - we've updated the version on pypi, and starting from version 0.1.0 this problem should be solved.
