### ISSUE TITLE
evaluateModel returns bad results on some computers when run in a browser

### ISSUE THREAD

**Issue by paulrosen** [spotify/basic-pitch#143]
**Describe the bug**
We are running basic pitch in production and we are getting a non-zero number of users who are getting bad results. We initially wrote it off to old devices but we got a message from a user that says, in part, "Our IT department has looked into this. They have found that our older Chromebooks with Intel processors worked well with the tool. However, the newer devices with AMD processors did not."

I'm not convinced it is related to the AMD processors, but I don't have any idea how to debug this and know what's wrong.

We do have a system that fails. We can run the exact same software with the same recording and get the same results on most computers, but we get much worse results on this one.

**To Reproduce**
It happens on some computers but not others. The code that fails is buried in our app but it isn't anything more complicated than running `evaluateModel`. I can make a simple app with just that function if that helps. Note that we can reproduce the problem using an audio file that contains separated pitches generated by midi.

**Expected behavior**
When passing a particular audio file to evaluateModel, I hope to have the results be the same on all computers and browsers, and those results be a good approximation of the pitches in the recording.

**Additional context**
What I hope to get from this report is either (or both), 1) some tools to help me debug the problem and perhaps some code that would allow me to detect whether the problem exists on that computer, or 2) an explanation of how the results could be different on different computers.

BTW, on most computers Basic Pitch works great and we're really excited about it!

**Comment by drubinstein** [comment]
Not sure I can personally help with this. Maybe @dohertyguirand can. But some ideas,

1. If you work at a place with a cloud provider you can try out your code there. For example, google's E2 machines use AMD
2. Can you confirm that the versions of all packages used are identical between the two machines
3. Make sure that both machines are using the same runner, e.g., it is not the case that one machine is using the tensorflow runner and another is using onnx.

**Comment by paulrosen** [comment]
Thanks for the quick response! This is in a web page so all users are going to the same URL and downloading the same code and model. 

However, I don't know what happens after I call the library so it is possible that it is analyzing the hardware and making different choices? I am just guessing.

I should have mentioned, my `package.json` file contains `"@spotify/basic-pitch": "1.0.1",`.

**Comment by drubinstein** [comment]
Ahhhh. Because this isn't the [basic-pitch-ts](https://github.com/spotify/basic-pitch-ts) repo, I assumed this was a python project.

TFJS which basic-pitch-ts uses under the hood can make different choices, e.g. WebGPU vs wasm. You can check/set your backend with [tf.getBackend() and tf.setBackend()](https://www.tensorflow.org/js/guide/platform_environment)

**Comment by paulrosen** [comment]
Sorry for opening this in the wrong repo -

I upgraded tensorflow in the ts repo and added:
```
"@tensorflow/tfjs-backend-wasm": "4.21.0",
"@tensorflow/tfjs-backend-webgpu": "^4.21.0",
```
to my package.json.

Then in my code:
```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-backend-wasm';
import '@tensorflow/tfjs-backend-webgpu';

await tf.setBackend('wasm')
-- or --
await tf.setBackend('webgpu')
```
And with a quick test, it looks like it worked! Those computers are acting weird just for the 'webgl' type backend.

Anyway, thanks so much for the clue! We never would have figured that out.
