### ISSUE TITLE
 ValueError: File ...basic_pitch/saved_models/icassp_2022/nmp cannot be loaded into either TensorFlow, CoreML, TFLite or ONNX. Please check if it is a supported and valid serialized model and that one of these packages are installed. On this system, ['TensorFlow', 'TensorFlowLite'] is installed.

### ISSUE THREAD

**Issue by marypilataki** [spotify/basic-pitch#150]
Hello,

Given the following code where f is the path to an audio file:

```
from basic_pitch.inference import predict
model_output, midi_data, note_events = predict(f)

```
I encounter the following error: 
_ValueError: File ...basic_pitch/saved_models/icassp_2022/nmp cannot be loaded into either TensorFlow, CoreML, TFLite or ONNX. Please check if it is a supported and valid serialized model and that one of these packages are installed. On this system, ['TensorFlow', 'TensorFlowLite'] is installed._

I found the error message confusing because there is an existing tensorflow installation in my virtual environment for sure. Could you please assist me with this? I use python 3.10.13 and tensorflow-cpu==2.16.1. Same problem persists when install tensorflow==2.18.0 instead.

Many thanks,
Mary

**Comment by drubinstein** [comment]
Per the [dependencies](https://github.com/spotify/basic-pitch/blob/53f67386556154f801845cdab579666e11d2e827/pyproject.toml#L30), basic-pitch is currently supported for `tensorflow<2.15.1`.

**Comment by marypilataki** [comment]
Thanks for the response!

I can confirm that I am able to successfully run the above snippet in a Python 3.11.6 environment with tensorflow 2.15.0 installed. It also works in a conda environment, Python version 3.10.15 and tensorflow version 2.17.0.

**Comment by marypilataki** [comment]
- Python 3.11.6 with tensorflow 2.15.0 (python venv)
- Python 3.10.15 with tensorflow version 2.17.0 (conda env)
