### ISSUE TITLE
Keras.io tutorial?

### ISSUE THREAD

**Issue by LukeWood** [spotify/basic-pitch#16]
Hey everyone!  I’m Luke - I work full time on keras.  I think you have a really great core base here for audio processing.  There aren’t a ton of code samples that use Keras for audio processing right now.

would you guys be interested in contributing a keras.io tutorial showcasing some of your work?

**Comment by LukeWood** [comment]
I think showing off how to implement some of the layers and explaining what they do would be a great tutorial!  

Additionally diffusing some of the knowledge you have on using Keras models to process audio would be really valuable to the community!

**Comment by drubinstein** [comment]
Thanks for the enthusiasm. I talked it over internally with my team and we saw that as much as we want to contribute to keras, we don't have the ability to add that task to our quarterly work. Hopefully we can in the future.

I'll leave this issue open for now and revive the thread when we have time in the future.
