### ISSUE TITLE
Difference in pitch bend behavior

### ISSUE THREAD

**Issue by neo-anderson** [spotify/basic-pitch#17]
If you playback the output MIDI in VLC player and compare it with the rendered audio, the pitch bends sound different. The sonified audio on the webapp and the corresponding MIDI sound different from the output of the pip installed version.

**Comment by rabitt** [comment]
@neo-anderson this is not too surprising to hear - not all midi rendering engines support pitch bends. As of now, the webapp doesn't support pitchbend playback either (just visualization & export). However, the rendered audio (when passing the `--sonify` flag to the predict script) will render the pitch bends.

**Comment by neo-anderson** [comment]
That makes sense. Thank you
