### ISSUE TITLE
Open sourcing JavaScript version

### ISSUE THREAD

**Issue by tomduncalf** [spotify/basic-pitch#18]
Hey,

Really cool library, pretty impressive results.

I wondered if you had any plans to open source the JS version, or provide instructions on how to use the model with Tensorflow.js?

Thanks,
Tom

**Comment by rabitt** [comment]
@tomduncalf in short, yes! The javascript version should be out very soon! (cc @drubinstein )

**Comment by tomduncalf** [comment]
Awesome, thanks @rabitt!
