### ISSUE TITLE
Web version parameters vs function arguments

### ISSUE THREAD

**Issue by neo-anderson** [spotify/basic-pitch#27]
How do the web app parameters Note Segmentation and Model Confidence Threshold work? Is it possible to map their behavior using `predict_and_save` function arguments?

**Comment by drubinstein** [comment]
Hi they map to [outputToNotesPoly](https://github.com/spotify/basic-pitch-ts/blob/main/src/toMidi.ts#L342) in our typescript repo and [this function in this repo](https://github.com/spotify/basic-pitch/blob/main/basic_pitch/note_creation.py#L46).

They correspond to:
```
  OnsetThreshold = 'Note Segmentation',
  FrameThreshold = 'Model Confidence Threshold',
  MinimumNoteLength = 'Minimum Note Length',
  InferOnsets = 'Boost Onsets',
  MaxFreq = 'Maximum Pitch',
  MinFreq = 'Minimum Pitch',
```

**Comment by neo-anderson** [comment]
Appreciate the help. Thanks, @drubinstein
