### ISSUE TITLE
About page is not working

### ISSUE THREAD

**Issue by yadunandanbhat** [spotify/basic-pitch#4]
See below image
![image](https://user-images.githubusercontent.com/54680617/168085896-a86439bd-6513-4a84-b48e-dcad07479f10.png)
And also the links in the readme say "basicpitch.io" while the actual link is "https://basicpitch.spotify.com/".

**Comment by rabitt** [comment]
@yadunandanbhat Thanks for reporting this! We're still working on the about page, it should be up soon. 

> And also the links in the readme say "basicpitch.io" while the actual link is "https://basicpitch.spotify.com/".'

Both links should work, basicpitch.io redirects to https://basicpitch.spotify.com/

**Comment by rabitt** [comment]
This is fixed! https://basicpitch.spotify.com/about
