### ISSUE TITLE
What is the default pitch bend range? [question]

### ISSUE THREAD

**Issue by rhelsing** [spotify/basic-pitch#43]
On a synth, I am using -2 <-> +2 and it sounds odd so I'm assuming there is a range that works best?

**Comment by rhelsing** [comment]
After running a few experiments, it seems like it is -2, +2?

**Comment by bgenchel** [comment]
You got it! [See here](https://github.com/spotify/basic-pitch/blob/main/basic_pitch/note_creation.py#L255)
