### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by sonovice** [spotify/basic-pitch#51]
Thank you very much for open sourcing this valuable code. Any chance on also releasing the training code to build upon your research and fine tune the model? Probably not too hard to implement the three losses from the paper, but having the "original" would be nice. :)

(Was also briefly mentioned in #21, but I think it is worth an own issue.)

**Comment by eunkoh** [comment]
Hi, any updates on this training code release? I could see another branch has `train.py`, but want to make sure getting original `train.py` from the team. Thank you in advance! [https://github.com/spotify/basic-pitch/blob/drubinstein/wip-training/basic_pitch/train.py]

**Comment by johngao2** [comment]
No significant updates, but yes that branch has the original train.py that was built internally.

**Comment by johngao2** [comment]
Closing as duplicate, please see https://github.com/spotify/basic-pitch/pull/38 for in-progress work regarding training code
