### ISSUE TITLE
Documentation Append Request

### ISSUE THREAD

**Issue by AdamMason1877** [spotify/basic-pitch#68]
Basic Pitch for the end user who clones the repo is confusing as the documentation indicates to use the syntax: `basic-pitch <output directory> <input file>
`
No indication is provided as to whether <> should be included. Including some examples of varying complexities could aid new users.

**Comment by dohertyguirand** [comment]
Hey Adam, Thanks for your message. Users will need to remove the triangle brackets (<>) when inputting the output directory and input file. I will add a note in the documentation to make it more clear 😄 .
