### ISSUE TITLE
Basic Pitch in an audio plugin

### ISSUE THREAD

**Issue by DamRsn** [spotify/basic-pitch#71]
Hey,

I've created an audio-to-midi VST/AU plugin that uses Basic Pitch internally. It's called NeuralNote and with it anyone can now have Basic Pitch's capabilities directly in their DAW! 

Everything's open source, the repo is https://github.com/DamRsn/NeuralNote . Feel free to check it out!

Thank you for this amazing work that is Basic Pitch!

**Comment by bgenchel** [comment]
Hi Damien! 

Thank you so much for your work on this. It works great! We'll add it to the README :)

**Comment by DamRsn** [comment]
That's great, thank you!

**Comment by AlleyWei** [comment]
@DamRsn We'd love to share this plugin on our Spotify R&D channels! Can you confirm if you are okay with us featuring you and this plugin on Twitter and Linkedin, as well as your preferred handles? Thank you!

**Comment by DamRsn** [comment]
Yes for sure go ahead! Here's my [LinkedIn profile](https://www.linkedin.com/in/damien-ronssin/). I don't have a Twitter account but feel free to share it there as well. Thank you!

**Comment by AlleyWei** [comment]
@DamRsn thank you!
