### ISSUE TITLE
Feature Request: Some way to adjust granularity

### ISSUE THREAD

**Issue by slimandslam** [spotify/basic-pitch#72]
Feature request: Some way to adjust granularity.  It seems that it's too good at interpreting 1/32 rests and stuff like that. 
If I know in advance that my audio has, say, nothing shorter than an eighth note or eighth rest, I'd like to be able to give
that info to the app and have it round off anything it analyzes to the nearest eighth note/rest.

**Comment by johngao2** [comment]
Hi! I think the feature that might work for you is minimum note length parameter. We have a slider for it in the web app, and you can also set it as a command line argument. That being said, the parameter takes note length in milliseconds, so you'll also need the song's BPM if you want to round to eighth notes, for instance. Hope that helps!
