### ISSUE TITLE
Realtime detection

### ISSUE THREAD

**Issue by bfrasure** [spotify/basic-pitch#85]
Has anyone been successful in using this technology for near real-time detection?

**Comment by LDMFD** [comment]
@johngao2 / others on the team, any prelim ideas if this would be possible?

**Comment by johngao2** [comment]
Unfortunately the answer seems to be no at the moment. @DamRsn wrote a great summary of it [here](https://github.com/DamRsn/NeuralNote#could-neuralnote-transcribe-audio-in-real-time).

**Comment by LDMFD** [comment]
Thanks for the info!

Awesome project btw, +1 for Spotify! :-)
