### ISSUE TITLE
Support for stream in/out?

### ISSUE THREAD

**Issue by mickaelistria** [spotify/basic-pitch#91]
I see basic-pitch easily process audio files and produces midi files. And I also notice its performance are very good locally: 11s to process a 3 minutes track (and 5 of this 11 seconds are about "Importing Tensorflow").
So I'm wondering whether it would be doable for basic pitch to take audio stream as input? And produce "on the fly" (even with some delay) a midi out stream (basically behave as a midi out device)? Or does it need to have the whole audio content available beforehand to process?

**Comment by drubinstein** [comment]
Thanks for the interest. This question was previously discussed in Issue #19. You asked correctly, basic-pitch requires the entirety of the audio before the post processing step.
